model: 'pointnet' # pointnet 
task: 'cls' # cls or seg
mode: 'train' # debug or train 

seed: 42

data: 
    batch_size: 32
    num_workers: 4
    num_points: 2500
    data_dir: './data/shapenet'
    dataset_type: 'shapenet' # shapenet or modelnet40 or hyundai(custom)
    class_choice: []
    data_augmentation: True
    
callbacks: 
    patience: 50

train:
    devices: [0]
    accelerator: 'gpu'
    pretrain_path: ''
    min_epochs: 1
    max_epochs: 200
    lr: 0.001
    feature_transform: True # True or False